// handleing of API requests and K2 API integration code generated by ChatGPT
// content for diagnostic reasoning written by Alisha Owaise
console.log("RUNNING PROGRAMMMMM");

import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import axios from "axios";

dotenv.config();
console.log("1");

const app = express();

// middleware
app.use(cors());
app.use(express.json());

// load API key securely
const K2_API_KEY = process.env.K2_API_KEY;
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY; //NVIDIA: Nemotron 3 Super

console.log("2");
/**
 * MAIN DIAGNOSTIC ENDPOINT
 * Orchid frontend will call this
 */
app.post("/diagnose", async (req, res) => {
  try {
    const { messages } = req.body;

    // Inject SYSTEM PROMPT (your reasoning engine)
    const fullMessages = [
      {
        role: "system",
        content: `
You are AutoFix2000, an expert AI car diagnostic reasoning system.

You MUST:
- Act like a mechanic using step-by-step reasoning
- Generate multiple hypotheses with probabilities
- Ask one question at a time
- Adapt question type (yes/no, multiple choice, text, inspection)
- prioritize questions that maximize information gain and minimize cost
- prioritize low-cost questions (e.g. "Is the check engine light on?") before high-cost ones (e.g. "Inspect the fuel pump")
- prioritize questions that can rule out multiple issues at once
- if suggesting an inspection, provide clear instructions on what to check and what to look for
- you MUST always start with asking information about the car make, model, and year.
- ask subsequent relevant information about the car as needed
- for suggestions that require user input, provide clear guidance on how to find the answer every time.
- for suggestions you MUST ALWAYS include information on where exactly to look. 
- ALWAYS define key car terms. Keep a mindset that the user knows almost nothing about cars except the basic functions.
- if recieving a response inquiring about how to do something, you MUST provide background information, and then ask if they've understood before asking about the result.
- adapt suggestions for user skill level (e.g. "If you're comfortable checking the oil level, please do so and let me know what you find")
- Update probabilities after each response
- Avoid final answers unless confidence > 0.85
- Estimate waste prevented (money + environmental impact)
- ALWAYS provide options for answers. If not applicable, accept text input.



Always respond in structured JSON:
{
  "question": "...",
  "question_type": "yes_no | multiple_choice | text_input | inspection",
  "options": [],
  "hypotheses": [
    {
      "issue": "...",
      "probability": 0.0,
      "reason": "..."
    }
  ],
  "recommendation": "...",
  "waste_prevented": {
    "money_saved_estimate": "...",
    "environmental_impact": "..."
  },
  "confidence": 0.0,
  "reasoning_summary": "..."

  At the end of each of your responses, include this JSON format cleanly. Do not include any additional information after it. ALWAYS do this.
}
        `.trim()
      },
      ...messages
    ];

  console.log("before call");

    // CALL K2 API 
    const response = await axios.post(
      "https://api.k2think.ai/v1/chat/completions",
      {
        model: "MBZUAI-IFM/K2-Think-v2",
        messages: fullMessages,
        stream: false
      },
      {
        headers: {
          Authorization: `Bearer ${K2_API_KEY}`,
          "Content-Type": "application/json",
          accept: "application/json"
        }
      }
    );

    console.log("attempted");
    const rawContent = response.data.choices[0].message.content;
    console.log("Raw K2 Response:", rawContent);
    
    let parsed;


    try {
      parsed = JSON.parse(rawContent);
    }
    catch {
      // 2. Try regex extract
      const match = rawContent.match(/\{[\s\S]*\}/);
      if (match) {
        try {
          parsed = JSON.parse(match[0]);
        } catch {

          // 3. Fallback to NVIDIA
          console.log("Sending to Elephant...");
          const gemmaRes = await axios.post(
            "https://openrouter.ai/api/v1/chat/completions",
            {
              model: "openrouter/elephant-alpha",
              messages: [{
                role: "user",
                content: `Extract and return ONLY the JSON object from this text. No explanation, no markdown, just raw JSON:\n\n${rawContent}`
              }],
              max_tokens: 1024
            },
            {
              headers: {
                Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
                "Content-Type": "application/json"
              }
            }
          );
          const gemmaContent = gemmaRes.data.choices[0].message.content;
          console.log("RAW GEMMA:", gemmaContent);
          const start = gemmaContent.indexOf('{');
          const end = gemmaContent.lastIndexOf('}');
          if (start === -1 || end === -1) throw new Error("Gemma couldn't extract JSON");
          parsed = JSON.parse(gemmaContent.slice(start, end + 1));

        }
      }
    }

    console.log("PARSED ATTEMPT:", JSON.stringify(parsed).slice(0, 200));
    res.json(parsed);

  } catch (error) {
    console.error("K2 Error:", error.response?.data || error.message);
    res.status(500).json({
      error: "K2 request failed",
      details: error.message
    });
  }
});

// start server
const PORT = 3000;
app.listen(PORT, () => {
  console.log(`AutoFix2000 backend running on http://localhost:${PORT}`);
});


